<?php
declare(strict_types=1);

const ROLE_ADMIN = 'ADMIN';
const ROLE_ARMEIRO = 'ARMEIRO';
const ROLE_POLICIAL = 'POLICIAL';

const WEAPON_STATUS_DISPONIVEL = 'DISPONIVEL';
const WEAPON_STATUS_CAUTELADA = 'CAUTELADA';
const WEAPON_STATUS_INATIVA = 'INATIVA';

const VEST_STATUS_DISPONIVEL = 'DISPONIVEL';
const VEST_STATUS_CAUTELADO = 'CAUTELADO';
const VEST_STATUS_INATIVO = 'INATIVO';

const PASSWORD_GATE_MAX_ATTEMPTS = 5;
const PASSWORD_GATE_WINDOW_SECONDS = 300;
const SESSION_IDLE_TIMEOUT_SECONDS = 3600;
